name: flutter_project_structure
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  intl: ^0.18.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  http_client:
    path: package/http_client
  go_router: ^13.2.4
  loader_overlay: ^4.0.0
  loading_indicator: ^3.1.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
  generate: true
